debug: False 
dataset: "/media/pecneb/970evoplus/cv_research_video_dataset/Bellevue_116th_NE12th_24h/"
model:
  # - SVM
  # - KNN
  - DT
  # - MLP
output: "/media/pecneb/970evoplus/cv_research_video_dataset/Bellevue_116th_NE12th_24h/"
feature_vector_version:
  # - "1"
  # - "1_SG_transform"
  # - "7"
  # - "7_SG_transform"
  # - "Re"
  # - "ReVe"
  # - ReVeAe
  # - "ReRs"
  - ReVeRs
  # - ReVeAeRs
  # - ReRm
  # - ReVeRm
  # - ReVeAeRm
  # - ReRsRm
  # - ReVeRsRm
  # - ReVeAeRsRm
min_samples: 100
xi: 0.05
max_eps: 0.15
mse: 0.2
n_jobs: 8
cross_validation: False
grid_search: False
fov_correction: True
video_path: "/media/pecneb/970evoplus/cv_research_video_dataset/Bellevue_116th_NE12th/Bellevue_116th_NE12th__2017-09-11_00-08-29.mp4"
google_map_image: "/media/pecneb/970evoplus/cv_research_video_dataset/Google_Maps_Pics/Bellevue_116th_NE12th_google_maps.png"
distance: 254 # Bellevue 116th NE12th
max_stride: 30
window_length: 7
preprocessing:
  enter_exit_distance: 
    switch: True
    threshold: 0.4
  edge_distance:
    switch: True
    threshold: 0.7
  detection_distance:
    switch: False
    threshold: 0.01
  filling: False