debug: False 
dataset: "/media/pecneb/970evoplus/cv_research_video_dataset/Bellevue_150th_Newport_24h_v2"
model:
  # - SVM
  # - KNN
  # - DT
  - MLP
output: "/media/pecneb/970evoplus/cv_research_video_dataset/Bellevue_150th_Newport_24h_v2"
feature_vector_version:
  # - "1"
  # - "1_SG_transform"
  # - "7"
  # - "7_SG_transform"
  # - "Re"
  # - "ReVe"
  # - ReVeAe
  # - "ReRs"
  - ReVeRs
  # - ReVeAeRs
  # - ReRm
  # - ReVeRm
  # - ReVeAeRm
  # - ReRsRm
  # - ReVeRsRm
  # - ReVeAeRsRm
min_samples: 200
xi: 0.05
max_eps: 0.1
mse: 0.2
n_jobs: 8
cross_validation: False
grid_search: False
fov_correction: True
video_path: "/media/pecneb/970evoplus/cv_research_video_dataset/Bellevue_150th_Newport/Bellevue_150th_Newport__2017-09-11_05-08-29.mp4"
google_map_image: "/media/pecneb/970evoplus/cv_research_video_dataset/Google_Maps_Pics/Bellevue_150th_Newport_google_maps.png"
distance: 300 # Bellevue 150th Newport/Eastgate
max_stride: 30
window_length: 7
preprocessing:
  enter_exit_distance: 
    switch: True
    threshold: 0.4
  edge_distance:
    switch: True
    threshold: 0.7
  detection_distance:
    switch: False
    threshold: 0.01
  filling: False