debug: False
# dataset: "/media/pecneb/970evoplus/cv_research_video_dataset/Bellevue_150th_Newport_24h_v2/Bellevue_150th_Newport_24h.json"
# dataset: "/media/pecneb/970evoplus/cv_research_video_dataset/Bellevue_116th_NE12th_24h/Bellevue_116th_NE12th.json"
# dataset: "/media/pecneb/970evoplus/cv_research_video_dataset/Bellevue_150th_SE38th_24h/Bellevue_150th_SE38th_24h.json"
# dataset: "/media/pecneb/970evoplus/cv_research_video_dataset/Bellevue_NE8th_24h_v2/Bellevue_NE8th_24h.json"
dataset: "/media/pecneb/970evoplus/cv_research_video_dataset/Bellevue_Eastgate_24h/Bellevue_Eastgate_24h.json"
model:
  - SVM
  - KNN
  # - DT
  - MLP
# output: "/media/pecneb/970evoplus/cv_research_video_dataset/Bellevue_NE8th_24h_v2/"
# output: "/media/pecneb/970evoplus/cv_research_video_dataset/Bellevue_150th_SE38th_24h/"
output: "/media/pecneb/970evoplus/cv_research_video_dataset/Bellevue_Eastgate_24h/"
feature_vector_version: # ReVeRs & ReVeRm & ReVeRsRm &  ReVeAeRsRm
  # - "1"
  # - "1_SG_transform"
  # - "7"
  # - "7_SG_transform"
  - "Re"
  - "ReVe"
  - ReVeAe
  - "ReRs"
  - ReVeRs
  - ReVeAeRs
  - ReRm
  - ReVeRm
  - ReVeAeRm
  - ReRsRm
  - ReVeRsRm
  - ReVeAeRsRm
min_samples: 200
xi: 0.1
max_eps: 0.16
mse: 0.2
n_jobs: 8
cross_validation: False
grid_search: False
fov_correction: False 
# video_path: "/media/pecneb/970evoplus/cv_research_video_dataset/Bellevue_150th_Newport/Bellevue_150th_Newport__2017-09-11_05-08-29.mp4"
# video_path: "/media/pecneb/970evoplus/cv_research_video_dataset/Bellevue_116th_NE12th/Bellevue_116th_NE12th__2017-09-11_00-08-29.mp4"
# video_path: "/media/pecneb/970evoplus/cv_research_video_dataset/Bellevue_Bellevue_NE8th/Bellevue_Bellevue_NE8th__2017-09-11_04-08-29.mp4"
# video_path: "/media/pecneb/970evoplus/cv_research_video_dataset/Bellevue_150th_SE38th/Bellevue_150th_SE38th__2017-09-11_04-08-29.mp4"
video_path: "/media/pecneb/970evoplus/cv_research_video_dataset/Bellevue_150th_Eastgate/Bellevue_150th_Eastgate__2017-09-11_09-08-31.mp4"
# google_map_image: "/media/pecneb/970evoplus/cv_research_video_dataset/Google_Maps_Pics/Bellevue_NE8th.png"
# google_map_image: "/media/pecneb/970evoplus/cv_research_video_dataset/Google_Maps_Pics/Bellevue_150th_SE38th_google_maps.png"
# google_map_image: "/media/pecneb/970evoplus/cv_research_video_dataset/Google_Maps_Pics/Bellevue_116th_NE12th_google_maps.png"
# google_map_image: "/media/pecneb/970evoplus/cv_research_video_dataset/Google_Maps_Pics/Bellevue_150th_Newport_google_maps.png"
google_map_image: "/media/pecneb/970evoplus/cv_research_video_dataset/Google_Maps_Pics/Bellevue_150th_Eastgate_google_maps.png"
# google_map_image: "/media/pecneb/970evoplus/cv_research_video_dataset/Google_Maps_Pics/Bellevue_NE8th.png"
# distance: 254 # Bellevue 116th NE12th
distance: 300 # Bellevue 150th Newport/Eastgate
# distance: 260 # Bellevue 150th SE38th
# distance: 250 # Bellevue NE8th 116th
max_stride: 30
window_length: 7
preprocessing:
  enter_exit_distance:
    switch: True
    threshold: 0.4
  edge_distance:
    switch: True
    threshold: 0.7
  detection_distance:
    switch: False
    threshold: 0.01
  filling: False
num_runs: 5
dataset_fraction: 1
statistics_only: False 
