debug: True
dataset: "/media/pecneb/970evoplus/cv_research_video_dataset/Bellevue_116th_NE12th_24h"
enter_exit_threshold: 0.4
edge_distance_threshold: 0.7
detection_distance_threshold: 0.01
model:
  - SVM
  - KNN
  - DT
output: "/media/pecneb/970evoplus/cv_research_video_dataset/Bellevue_116th_NE12th_24h"
feature_vector_version:
  # - "1"
  # - "1_SG_transform"
  - "7"
  # - "7_SG_transform"
min_samples: 100
xi: 0.05
max_eps: 0.15
mse: 0.2
n_jobs: 8
cross_validation: False
grid_search: False
fov_correction: False
# video_path: "/media/pecneb/970evoplus/cv_research_video_dataset/Bellevue_150th_Newport/Bellevue_150th_Newport__2017-09-11_05-08-29.mp4" 
video_path: "/media/pecneb/970evoplus/cv_research_video_dataset/Bellevue_116th_NE12th/Bellevue_116th_NE12th__2017-09-11_00-08-29.mp4" 
# video_path: "/media/pecneb/970evoplus/cv_research_video_dataset/Bellevue_Bellevue_NE8th/Bellevue_Bellevue_NE8th__2017-09-11_04-08-29.mp4"
# video_path: "/media/pecneb/970evoplus/cv_research_video_dataset/Bellevue_150th_SE38th/Bellevue_150th_SE38th__2017-09-11_04-08-29.mp4"
# video_path: "/media/pecneb/970evoplus/cv_research_video_dataset/Bellevue_150th_Eastgate/Bellevue_150th_Eastgate__2017-09-11_09-08-31.mp4"
# google_map_image: "/media/pecneb/970evoplus/cv_research_video_dataset/Google_Maps_Pics/Bellevue_NE8th.png"
# google_map_image: "/media/pecneb/970evoplus/cv_research_video_dataset/Google_Maps_Pics/Bellevue_150th_SE38th_google_maps.png"
google_map_image: "/media/pecneb/970evoplus/cv_research_video_dataset/Google_Maps_Pics/Bellevue_116th_NE12th_google_maps.png"
distance: 254 # Bellevue 116th NE12th
# distance: 300 # Bellevue 150th Newport/Eastgate
# distance: 260 # Bellevue 150th SE38th
# distance: 250 # Bellevue NE8th 116th